/**
 * YouTube Captions Extractor
 * Free alternative to Gladia for videos that have captions available
 */

import logger from '@/lib/logger';

export interface CaptionTrack {
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  url: string;
}

export interface CaptionSegment {
  text: string;
  start: number; // seconds
  duration: number; // seconds
}

/**
 * Check if a YouTube video has captions available
 */
export async function hasYouTubeCaptions(videoId: string, apiKey: string): Promise<boolean> {
  try {
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${videoId}&key=${apiKey}`
    );

    if (!response.ok) {
      return false;
    }

    const data = await response.json();

    // Check if video has captions
    // Note: This is a simplified check. The actual caption availability
    // is in the contentDetails.caption field
    const captionResponse = await fetch(
      `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}&key=${apiKey}`
    );

    if (captionResponse.ok) {
      const captionData = await captionResponse.json();
      return captionData.items && captionData.items.length > 0;
    }

    return false;
  } catch (error) {
    logger.error({ error, videoId }, 'Failed to check for YouTube captions');
    return false;
  }
}

/**
 * Get available caption tracks for a video
 * Note: This requires OAuth 2.0 authentication for most videos
 */
export async function getCaptionTracks(videoId: string, apiKey: string): Promise<CaptionTrack[]> {
  try {
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}&key=${apiKey}`
    );

    if (!response.ok) {
      throw new Error(`YouTube Captions API error: ${response.status}`);
    }

    const data = await response.json();

    if (!data.items || data.items.length === 0) {
      return [];
    }

    return data.items.map((item: any) => ({
      language: item.snippet.language,
      languageCode: item.snippet.language,
      isAutoGenerated: item.snippet.trackKind === 'asr',
      url: '', // YouTube API doesn't provide direct download URLs
    }));
  } catch (error) {
    logger.error({ error, videoId }, 'Failed to get caption tracks');
    return [];
  }
}

/**
 * Extract captions using youtubei.js (works without bot detection for many videos)
 * This is the method used in your youtube-audio-downloader Apify actor
 */
export async function extractCaptionsWithYoutubeI(videoId: string): Promise<{
  success: boolean;
  transcript: string;
  segments: CaptionSegment[];
  error?: string;
}> {
  try {
    // Import youtubei.js dynamically
    const { Innertube } = await import('youtubei.js');

    console.log(`\n📝 Attempting to extract captions with youtubei.js...`);
    const youtube = await Innertube.create();

    const info = await youtube.getInfo(videoId);
    const transcriptData = await info.getTranscript();

    if (!transcriptData) {
      return {
        success: false,
        transcript: '',
        segments: [],
        error: 'No captions available for this video',
      };
    }

    // Convert to our format - youtubei.js structure varies by version
    // Try to extract segments from the transcript data
    let segments: CaptionSegment[] = [];
    let fullTranscript = '';

    // The transcript data structure can vary, so we handle it flexibly
    if (Array.isArray(transcriptData)) {
      // If it's already an array of segments
      segments = transcriptData.map((segment: any) => ({
        text: segment.text || segment.snippet?.text || '',
        start: (segment.start_ms || segment.start || 0) / 1000,
        duration: ((segment.end_ms || segment.end || 0) - (segment.start_ms || segment.start || 0)) / 1000,
      }));
    } else if (typeof transcriptData === 'object' && 'actions' in transcriptData) {
      // YouTube's transcript format with actions
      const actions = (transcriptData as any).actions || [];
      segments = actions
        .filter((action: any) => action?.updateEngagementPanelAction)
        .flatMap((action: any) => {
          const content = action.updateEngagementPanelAction?.content;
          if (content?.transcriptRenderer?.body?.transcriptBodyRenderer?.cueGroups) {
            return content.transcriptRenderer.body.transcriptBodyRenderer.cueGroups.map((cue: any) => ({
              text: cue.transcriptCueGroupRenderer?.cues?.[0]?.transcriptCueRenderer?.cue?.simpleText || '',
              start: parseInt(cue.transcriptCueGroupRenderer?.cues?.[0]?.transcriptCueRenderer?.startOffsetMs || '0') / 1000,
              duration: parseInt(cue.transcriptCueGroupRenderer?.cues?.[0]?.transcriptCueRenderer?.durationMs || '0') / 1000,
            }));
          }
          return [];
        });
    }

    fullTranscript = segments.map(s => s.text).join(' ').trim();

    if (!fullTranscript || segments.length === 0) {
      return {
        success: false,
        transcript: '',
        segments: [],
        error: 'Transcript data structure not recognized or empty',
      };
    }

    console.log(`✅ Successfully extracted captions`);
    console.log(`   Segments: ${segments.length}`);
    console.log(`   Length: ${fullTranscript.length} characters`);

    return {
      success: true,
      transcript: fullTranscript,
      segments,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.log(`⚠️  Caption extraction failed: ${errorMessage}`);

    return {
      success: false,
      transcript: '',
      segments: [],
      error: errorMessage,
    };
  }
}

/**
 * Estimate cost savings by using captions vs Gladia
 */
export function estimateCostSavings(durationSeconds: number): {
  gladiaCost: number;
  captionCost: number;
  savings: number;
} {
  const hours = durationSeconds / 3600;
  const gladiaCost = hours * 0.612;
  const captionCost = 0; // Free!

  return {
    gladiaCost: Math.round(gladiaCost * 100) / 100,
    captionCost: 0,
    savings: Math.round(gladiaCost * 100) / 100,
  };
}
