'use client'

import { motion } from 'framer-motion'
import { Brain, TrendingUp, AlertTriangle, CheckCircle } from 'lucide-react'

interface Insight {
  type: 'positive' | 'negative' | 'neutral'
  title: string
  description: string
  impact: 'high' | 'medium' | 'low'
}

interface InsightsPanelProps {
  insights: Insight[]
}

export default function InsightsPanel({ insights }: InsightsPanelProps) {
  const getIcon = (type: string) => {
    switch (type) {
      case 'positive':
        return <CheckCircle className="h-5 w-5 text-green-600" />
      case 'negative':
        return <AlertTriangle className="h-5 w-5 text-red-600" />
      default:
        return <TrendingUp className="h-5 w-5 text-brand-blue" />
    }
  }

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'high':
        return 'bg-red-100 text-red-800'
      case 'medium':
        return 'bg-yellow-100 text-yellow-800'
      default:
        return 'bg-green-100 text-green-800'
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, slideY: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white rounded-lg shadow-brand p-6 border-l-4 border-brand-blue"
    >
      <div className="flex items-center mb-6">
        <Brain className="h-6 w-6 text-brand-blue mr-2" />
        <h3 className="text-xl font-semibold text-dark-gray">AI Insights</h3>
        <span className="ml-auto bg-brand-blue/10 text-brand-blue px-2 py-1 rounded-full text-xs font-medium">
          Generated by AI
        </span>
      </div>

      <div className="space-y-4">
        {insights.map((insight, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.1 }}
            className="border border-light-gray rounded-lg p-4 hover:shadow-sm transition-shadow"
          >
            <div className="flex items-start space-x-3">
              <div className="flex-shrink-0 mt-0.5">
                {getIcon(insight.type)}
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="text-sm font-semibold text-dark-gray">
                    {insight.title}
                  </h4>
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${getImpactColor(insight.impact)}`}>
                    {insight.impact} impact
                  </span>
                </div>
                <p className="text-sm text-dark-gray/70">
                  {insight.description}
                </p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-6 pt-4 border-t border-light-gray">
        <p className="text-xs text-dark-gray/60 text-center">
          AI insights are generated based on budget data analysis and may not reflect official town positions.
        </p>
      </div>
    </motion.div>
  )
}
